# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directories:
      - "/"
      - "/JavaIM"
      - "/LibraryTransformers"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
  - package-ecosystem: "github-actions" # See documentation for possible values
    directories:
      - "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
