package org.yuezhikong.javaim;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.servlet.ServletComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.scheduling.annotation.EnableAsync;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
//@EnableAsync
//@EnableScheduling
//@ServletComponentScan
@SpringBootApplication
public class JavaimApplication {
	public static void main(String[] args) {
		SpringApplication.run(JavaimApplication.class, args);
	}
}

//@Slf4j
//@Controller
//@RequestMapping("/")
//@Configuration
//class IndexController {
//	@GetMapping("loginPage")
//	public ModelAndView login() {
//		ModelAndView modelAndView = new ModelAndView("login");
//		return modelAndView;
//	}
//}
